name: travel
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  smooth_page_indicator: ^1.0.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/sky/
    - assets/images/sky/1/
    - assets/images/sky/2/
    - assets/images/sky/3/
    - assets/images/sky/4/
    - assets/images/beach/
    - assets/images/beach/1/
    - assets/images/beach/2/
    - assets/images/beach/3/
    - assets/images/beach/4/
    - assets/images/history/
    - assets/images/history/1/
    - assets/images/history/2/
    - assets/images/history/3/
    - assets/images/history/4/
    - assets/images/meals/
    - assets/images/meals/1/
    - assets/images/meals/2/
    - assets/images/meals/3/
    - assets/images/meals/4/
    - assets/images/city/
    - assets/images/city/1/
    - assets/images/city/2/
    - assets/images/city/3/
    - assets/images/city/4/
    - assets/images/profiles/
    - assets/icons/
    - assets/images/slider/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Light.ttf
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf